name: Build

on:
  push:
    branches: [main]
    paths:
      - 'ci-cd-security/example-service/**'
  pull_request:
    branches: [main]
    paths:
      - 'ci-cd-security/example-service/**'

jobs:
  build:
    uses: TorinKS/kse-labs-trusted-workflows/.github/workflows/go-build.yaml@main
    with:
      go-version: '1.25.5'
      working-directory: ci-cd-security/example-service
